version: "3"
services:
  seejet-tracker:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/seejet-tracker
      - media_vol:/files/media
    command: >
      sh -c "python manage.py makemigrations &&
              python manage.py migrate &&
                python manage.py wait_for_db &&
                  python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SECRET_KEY
    depends_on:
      - db

  db:
    image: postgres:16.2-bullseye
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - postgres_db:$PGDATA

volumes:
  postgres_db:
  media_vol:
